export const linkedIn_url = "https://www.linkedin.com/in/yuktha-polepalli/"
export const resume_link = "https://drive.google.com/file/d/1QxMm5EAoGPf3nbpnipHM_Vp8mJOkrNqX/preview"
export const masters_transcript_link = "https://drive.google.com/file/d/1QMcP1VWFJWi4WLhCo-CC8kBZwWFNG36A/preview"
export const bachelors_transcript_link = "https://drive.google.com/file/d/1HPC7ff7W8C7LBHGehZ9VdVGHMzhzDJGR/preview"
export const resume_external_link = "https://drive.google.com/file/d/1QxMm5EAoGPf3nbpnipHM_Vp8mJOkrNqX/view?usp=sharing"
export const email_address = "pyuktha.99@gmail.com"
